// This file is autogenerated by the hyperdispatch compiler
/* eslint-disable camelcase */

const { c, b4a, assert, DispatchError, ERRORS } = require('hyperdispatch/runtime')
const { version, getEncoding, setVersion } = require('./messages.js')

const defaultVersion = version

class Router {
  constructor () {
    this._handler0 = null
    this._handler1 = null
    this._handler2 = null
    this._handler3 = null
    this._handler4 = null
    this._handler5 = null
    this._handler6 = null
    this._handler7 = null
    this._handler8 = null

    this._missing = 9
  }

  add (name, handler) {
    switch (name) {
      case '@tamaflow/add-invite':
        this._handler0 = handler
        break
      case '@tamaflow/add-chat':
        this._handler1 = handler
        break
      case '@tamaflow/remove-chats':
        this._handler2 = handler
        break
      case '@tamaflow/update-ai-state':
        this._handler3 = handler
        break
      case '@tamaflow/relay-request':
        this._handler4 = handler
        break
      case '@tamaflow/relay-response':
        this._handler5 = handler
        break
      case '@tamaflow/relay-cancel':
        this._handler6 = handler
        break
      case '@tamaflow/add-writer':
        this._handler7 = handler
        break
      case '@tamaflow/add-payslip':
        this._handler8 = handler
        break
      default:
        throw DispatchError.NONEXISTENT_ROUTE(name)
    }
    this._missing--
  }

  _checkAll () {
    assert(this._handler0 !== null, 'Missing handler for "@tamaflow/add-invite"')
    assert(this._handler1 !== null, 'Missing handler for "@tamaflow/add-chat"')
    assert(this._handler2 !== null, 'Missing handler for "@tamaflow/remove-chats"')
    assert(this._handler3 !== null, 'Missing handler for "@tamaflow/update-ai-state"')
    assert(this._handler4 !== null, 'Missing handler for "@tamaflow/relay-request"')
    assert(this._handler5 !== null, 'Missing handler for "@tamaflow/relay-response"')
    assert(this._handler6 !== null, 'Missing handler for "@tamaflow/relay-cancel"')
    assert(this._handler7 !== null, 'Missing handler for "@tamaflow/add-writer"')
    assert(this._handler8 !== null, 'Missing handler for "@tamaflow/add-payslip"')
  }

  async dispatch (message, context) {
    if (this._missing > 0) {
      this._checkAll()
    }

    setVersion(defaultVersion)

    const op = b4a.isBuffer(message) ? decode(message) : message

    switch (op.id) {
      case 0:
        return this._handler0(op.value, context)
      case 1:
        return this._handler1(op.value, context)
      case 2:
        return this._handler2(op.value, context)
      case 3:
        return this._handler3(op.value, context)
      case 4:
        return this._handler4(op.value, context)
      case 5:
        return this._handler5(op.value, context)
      case 6:
        return this._handler6(op.value, context)
      case 7:
        return this._handler7(op.value, context)
      case 8:
        return this._handler8(op.value, context)
      default:
        throw DispatchError.HANDLER_NOT_FOUND_BY_ID(op.id)
    }
  }
}

function encode (name, message, { version = defaultVersion } = {}) {
  const state = { buffer: null, start: 0, end: 0 }

  const route = getRouteByName(name)
  setVersion(version)

  c.uint.preencode(state, route.id)
  route.enc.preencode(state, message)

  state.buffer = b4a.allocUnsafe(state.end)
  c.uint.encode(state, route.id)
  route.enc.encode(state, message)

  return state.buffer
}

function decode (buffer, { version = defaultVersion } = {}) {
  const state = { buffer, start: 0, end: buffer.length }

  const id = c.uint.decode(state)
  const route = getRouteById(id)
  setVersion(version)

  const value = route.enc.decode(state)
  return { id, name: route.name, value }
}

const route0 = {
  name: '@tamaflow/add-invite',
  id: 0,
  enc: getEncoding('@tamaflow/invite')
}

const route1 = {
  name: '@tamaflow/add-chat',
  id: 1,
  enc: getEncoding('@tamaflow/chat-msg')
}

const route2 = {
  name: '@tamaflow/remove-chats',
  id: 2,
  enc: getEncoding('@tamaflow/chats-remove')
}

const route3 = {
  name: '@tamaflow/update-ai-state',
  id: 3,
  enc: getEncoding('@tamaflow/ai-state-update')
}

const route4 = {
  name: '@tamaflow/relay-request',
  id: 4,
  enc: getEncoding('@tamaflow/relay-request')
}

const route5 = {
  name: '@tamaflow/relay-response',
  id: 5,
  enc: getEncoding('@tamaflow/relay-response')
}

const route6 = {
  name: '@tamaflow/relay-cancel',
  id: 6,
  enc: getEncoding('@tamaflow/relay-cancel')
}

const route7 = {
  name: '@tamaflow/add-writer',
  id: 7,
  enc: getEncoding('@tamaflow/writer')
}

const route8 = {
  name: '@tamaflow/add-payslip',
  id: 8,
  enc: getEncoding('@tamaflow/payslip')
}

function getRouteByName (name) {
  switch (name) {
    case '@tamaflow/add-invite':
      return route0
    case '@tamaflow/add-chat':
      return route1
    case '@tamaflow/remove-chats':
      return route2
    case '@tamaflow/update-ai-state':
      return route3
    case '@tamaflow/relay-request':
      return route4
    case '@tamaflow/relay-response':
      return route5
    case '@tamaflow/relay-cancel':
      return route6
    case '@tamaflow/add-writer':
      return route7
    case '@tamaflow/add-payslip':
      return route8
    default:
      throw DispatchError.ROUTE_NOT_FOUND_BY_NAME(name)
  }
}

function getRouteById (id) {
  switch (id) {
    case 0:
      return route0
    case 1:
      return route1
    case 2:
      return route2
    case 3:
      return route3
    case 4:
      return route4
    case 5:
      return route5
    case 6:
      return route6
    case 7:
      return route7
    case 8:
      return route8
    default:
      throw DispatchError.HANDLER_NOT_FOUND_BY_ID(id)
  }
}

module.exports = {
  version,
  encode,
  decode,
  Router,
  DispatchError,
  ERRORS
}
