// This file is autogenerated by the hyperschema compiler
// Schema Version: 5
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 5

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @tamaflow/invite
const encoding0 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.buffer.preencode(state, m.invite)
    c.buffer.preencode(state, m.publicKey)
    c.int.preencode(state, m.expires)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.buffer.encode(state, m.invite)
    c.buffer.encode(state, m.publicKey)
    c.int.encode(state, m.expires)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.int.decode(state)

    return {
      id: r0,
      invite: r1,
      publicKey: r2,
      expires: r3
    }
  }
}

// @tamaflow/chat-msg
const encoding1 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.text)
    state.end++ // max flag is 1 so always one byte

    if (m.info) c.json.preencode(state, m.info)
  },
  encode(state, m) {
    const flags = m.info ? 1 : 0

    c.string.encode(state, m.id)
    c.string.encode(state, m.text)
    c.uint.encode(state, flags)

    if (m.info) c.json.encode(state, m.info)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      text: r1,
      info: (flags & 1) !== 0 ? c.json.decode(state) : null
    }
  }
}

// @tamaflow/chats-remove
const encoding2 = {
  preencode(state, m) {
    c.json.preencode(state, m.ids)
  },
  encode(state, m) {
    c.json.encode(state, m.ids)
  },
  decode(state) {
    const r0 = c.json.decode(state)

    return {
      ids: r0
    }
  }
}

// @tamaflow/ai-state
const encoding3 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.writerKey)
    state.end++ // max flag is 8 so always one byte

    if (m.modelId) c.string.preencode(state, m.modelId)
    if (m.modelName) c.string.preencode(state, m.modelName)
    if (m.loadedAt) c.int.preencode(state, m.loadedAt)
  },
  encode(state, m) {
    const flags =
      (m.modelId ? 1 : 0) | (m.modelName ? 2 : 0) | (m.loadedAt ? 4 : 0) | (m.accepting ? 8 : 0)

    c.buffer.encode(state, m.writerKey)
    c.uint.encode(state, flags)

    if (m.modelId) c.string.encode(state, m.modelId)
    if (m.modelName) c.string.encode(state, m.modelName)
    if (m.loadedAt) c.int.encode(state, m.loadedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      writerKey: r0,
      modelId: (flags & 1) !== 0 ? c.string.decode(state) : null,
      modelName: (flags & 2) !== 0 ? c.string.decode(state) : null,
      loadedAt: (flags & 4) !== 0 ? c.int.decode(state) : 0,
      accepting: (flags & 8) !== 0
    }
  }
}

// @tamaflow/ai-state-update
const encoding4 = {
  preencode(state, m) {
    state.end++ // max flag is 16 so always one byte

    if (m._writerKey) c.string.preencode(state, m._writerKey)
    if (m.modelId) c.string.preencode(state, m.modelId)
    if (m.modelName) c.string.preencode(state, m.modelName)
    if (m.loadedAt) c.int.preencode(state, m.loadedAt)
  },
  encode(state, m) {
    const flags =
      (m._writerKey ? 1 : 0) |
      (m.modelId ? 2 : 0) |
      (m.modelName ? 4 : 0) |
      (m.loadedAt ? 8 : 0) |
      (m.accepting ? 16 : 0)

    c.uint.encode(state, flags)

    if (m._writerKey) c.string.encode(state, m._writerKey)
    if (m.modelId) c.string.encode(state, m.modelId)
    if (m.modelName) c.string.encode(state, m.modelName)
    if (m.loadedAt) c.int.encode(state, m.loadedAt)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      _writerKey: (flags & 1) !== 0 ? c.string.decode(state) : null,
      modelId: (flags & 2) !== 0 ? c.string.decode(state) : null,
      modelName: (flags & 4) !== 0 ? c.string.decode(state) : null,
      loadedAt: (flags & 8) !== 0 ? c.int.decode(state) : 0,
      accepting: (flags & 16) !== 0
    }
  }
}

// @tamaflow/relay-request
const encoding5 = {
  preencode(state, m) {
    c.string.preencode(state, m.requestId)
    c.buffer.preencode(state, m.fromKey)
    c.buffer.preencode(state, m.toKey)
    c.json.preencode(state, m.messages)
    c.string.preencode(state, m.modelId)
    c.int.preencode(state, m.createdAt)
  },
  encode(state, m) {
    c.string.encode(state, m.requestId)
    c.buffer.encode(state, m.fromKey)
    c.buffer.encode(state, m.toKey)
    c.json.encode(state, m.messages)
    c.string.encode(state, m.modelId)
    c.int.encode(state, m.createdAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.json.decode(state)
    const r4 = c.string.decode(state)
    const r5 = c.int.decode(state)

    return {
      requestId: r0,
      fromKey: r1,
      toKey: r2,
      messages: r3,
      modelId: r4,
      createdAt: r5
    }
  }
}

// @tamaflow/relay-response
const encoding6 = {
  preencode(state, m) {
    c.string.preencode(state, m.requestId)
    c.buffer.preencode(state, m.fromKey)
    c.buffer.preencode(state, m.toKey)
    c.string.preencode(state, m.kind)
    state.end++ // max flag is 2 so always one byte

    if (m.text) c.string.preencode(state, m.text)
    if (m.error) c.json.preencode(state, m.error)
  },
  encode(state, m) {
    const flags = (m.text ? 1 : 0) | (m.error ? 2 : 0)

    c.string.encode(state, m.requestId)
    c.buffer.encode(state, m.fromKey)
    c.buffer.encode(state, m.toKey)
    c.string.encode(state, m.kind)
    c.uint.encode(state, flags)

    if (m.text) c.string.encode(state, m.text)
    if (m.error) c.json.encode(state, m.error)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      requestId: r0,
      fromKey: r1,
      toKey: r2,
      kind: r3,
      text: (flags & 1) !== 0 ? c.string.decode(state) : null,
      error: (flags & 2) !== 0 ? c.json.decode(state) : null
    }
  }
}

// @tamaflow/relay-cancel
const encoding7 = {
  preencode(state, m) {
    c.string.preencode(state, m.requestId)
    c.buffer.preencode(state, m.fromKey)
    c.buffer.preencode(state, m.toKey)
  },
  encode(state, m) {
    c.string.encode(state, m.requestId)
    c.buffer.encode(state, m.fromKey)
    c.buffer.encode(state, m.toKey)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)

    return {
      requestId: r0,
      fromKey: r1,
      toKey: r2
    }
  }
}

// @tamaflow/writer
const encoding8 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.key)
  },
  encode(state, m) {
    c.buffer.encode(state, m.key)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)

    return {
      key: r0
    }
  }
}

// @tamaflow/payslip
const encoding9 = {
  preencode(state, m) {
    const flags =
      ((version >= 3 && m.employeeId) ? 1 : 0) |
      ((version >= 3 && m.employeeName) ? 2 : 0) |
      ((version >= 3 && m.period) ? 4 : 0) |
      ((version >= 3 && m.grossPay) ? 8 : 0) |
      ((version >= 3 && m.netPay) ? 16 : 0) |
      ((version >= 3 && m.currency) ? 32 : 0) |
      ((version >= 3 && m.companyName) ? 64 : 0) |
      ((version >= 3 && m.createdAt) ? 128 : 0) |
      ((version >= 3 && m.sentAt) ? 256 : 0) |
      ((version >= 3 && m.templateId) ? 512 : 0)

    c.string.preencode(state, m.id)
    c.string.preencode(state, m.recipient)
    c.string.preencode(state, m.routeId)
    c.uint.preencode(state, flags)

    if (version >= 3 && m.employeeId) c.string.preencode(state, m.employeeId)
    if (version >= 3 && m.employeeName) c.string.preencode(state, m.employeeName)
    if (version >= 3 && m.period) c.string.preencode(state, m.period)
    if (version >= 3 && m.grossPay) c.string.preencode(state, m.grossPay)
    if (version >= 3 && m.netPay) c.string.preencode(state, m.netPay)
    if (version >= 3 && m.currency) c.string.preencode(state, m.currency)
    if (version >= 3 && m.companyName) c.string.preencode(state, m.companyName)
    c.json.preencode(state, m.html)
    if (version >= 3 && m.createdAt) c.int.preencode(state, m.createdAt)
    if (version >= 3 && m.sentAt) c.int.preencode(state, m.sentAt)
    if (version >= 3 && m.templateId) c.string.preencode(state, m.templateId)
  },
  encode(state, m) {
    const flags =
      ((version >= 3 && m.employeeId) ? 1 : 0) |
      ((version >= 3 && m.employeeName) ? 2 : 0) |
      ((version >= 3 && m.period) ? 4 : 0) |
      ((version >= 3 && m.grossPay) ? 8 : 0) |
      ((version >= 3 && m.netPay) ? 16 : 0) |
      ((version >= 3 && m.currency) ? 32 : 0) |
      ((version >= 3 && m.companyName) ? 64 : 0) |
      ((version >= 3 && m.createdAt) ? 128 : 0) |
      ((version >= 3 && m.sentAt) ? 256 : 0) |
      ((version >= 3 && m.templateId) ? 512 : 0)

    c.string.encode(state, m.id)
    c.string.encode(state, m.recipient)
    c.string.encode(state, m.routeId)
    c.uint.encode(state, flags)

    if (version >= 3 && m.employeeId) c.string.encode(state, m.employeeId)
    if (version >= 3 && m.employeeName) c.string.encode(state, m.employeeName)
    if (version >= 3 && m.period) c.string.encode(state, m.period)
    if (version >= 3 && m.grossPay) c.string.encode(state, m.grossPay)
    if (version >= 3 && m.netPay) c.string.encode(state, m.netPay)
    if (version >= 3 && m.currency) c.string.encode(state, m.currency)
    if (version >= 3 && m.companyName) c.string.encode(state, m.companyName)
    c.json.encode(state, m.html)
    if (version >= 3 && m.createdAt) c.int.encode(state, m.createdAt)
    if (version >= 3 && m.sentAt) c.int.encode(state, m.sentAt)
    if (version >= 3 && m.templateId) c.string.encode(state, m.templateId)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      recipient: r1,
      routeId: r2,
      employeeId: (version >= 3 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      employeeName: (version >= 3 && (flags & 2) !== 0) ? c.string.decode(state) : null,
      period: (version >= 3 && (flags & 4) !== 0) ? c.string.decode(state) : null,
      grossPay: (version >= 3 && (flags & 8) !== 0) ? c.string.decode(state) : null,
      netPay: (version >= 3 && (flags & 16) !== 0) ? c.string.decode(state) : null,
      currency: (version >= 3 && (flags & 32) !== 0) ? c.string.decode(state) : null,
      companyName: (version >= 3 && (flags & 64) !== 0) ? c.string.decode(state) : null,
      html: c.json.decode(state),
      createdAt: (version >= 3 && (flags & 128) !== 0) ? c.int.decode(state) : 0,
      sentAt: (version >= 3 && (flags & 256) !== 0) ? c.int.decode(state) : 0,
      templateId: (version >= 3 && (flags & 512) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @tamaflow/rag-search
const encoding10 = {
  preencode(state, m) {
    c.string.preencode(state, m.requestId)
    c.buffer.preencode(state, m.fromKey)
    c.buffer.preencode(state, m.toKey)
    c.string.preencode(state, m.query)
    state.end++ // max flag is 2 so always one byte

    if (version >= 4 && m.topK) c.int.preencode(state, m.topK)
    if (version >= 4 && m.createdAt) c.int.preencode(state, m.createdAt)
  },
  encode(state, m) {
    const flags = ((version >= 4 && m.topK) ? 1 : 0) | ((version >= 4 && m.createdAt) ? 2 : 0)

    c.string.encode(state, m.requestId)
    c.buffer.encode(state, m.fromKey)
    c.buffer.encode(state, m.toKey)
    c.string.encode(state, m.query)
    c.uint.encode(state, flags)

    if (version >= 4 && m.topK) c.int.encode(state, m.topK)
    if (version >= 4 && m.createdAt) c.int.encode(state, m.createdAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      requestId: r0,
      fromKey: r1,
      toKey: r2,
      query: r3,
      topK: (version >= 4 && (flags & 1) !== 0) ? c.int.decode(state) : 0,
      createdAt: (version >= 4 && (flags & 2) !== 0) ? c.int.decode(state) : 0
    }
  }
}

// @tamaflow/rag-search-result
const encoding11 = {
  preencode(state, m) {
    c.string.preencode(state, m.requestId)
    c.buffer.preencode(state, m.fromKey)
    c.buffer.preencode(state, m.toKey)
    c.json.preencode(state, m.results)
    state.end++ // max flag is 2 so always one byte

    if (version >= 5 && m.error) c.string.preencode(state, m.error)
    if (version >= 5 && m.createdAt) c.int.preencode(state, m.createdAt)
  },
  encode(state, m) {
    const flags = ((version >= 5 && m.error) ? 1 : 0) | ((version >= 5 && m.createdAt) ? 2 : 0)

    c.string.encode(state, m.requestId)
    c.buffer.encode(state, m.fromKey)
    c.buffer.encode(state, m.toKey)
    c.json.encode(state, m.results)
    c.uint.encode(state, flags)

    if (version >= 5 && m.error) c.string.encode(state, m.error)
    if (version >= 5 && m.createdAt) c.int.encode(state, m.createdAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.json.decode(state)
    const flags = c.uint.decode(state)

    return {
      requestId: r0,
      fromKey: r1,
      toKey: r2,
      results: r3,
      error: (version >= 5 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      createdAt: (version >= 5 && (flags & 2) !== 0) ? c.int.decode(state) : 0
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@tamaflow/invite':
      return encoding0
    case '@tamaflow/chat-msg':
      return encoding1
    case '@tamaflow/chats-remove':
      return encoding2
    case '@tamaflow/ai-state':
      return encoding3
    case '@tamaflow/ai-state-update':
      return encoding4
    case '@tamaflow/relay-request':
      return encoding5
    case '@tamaflow/relay-response':
      return encoding6
    case '@tamaflow/relay-cancel':
      return encoding7
    case '@tamaflow/writer':
      return encoding8
    case '@tamaflow/payslip':
      return encoding9
    case '@tamaflow/rag-search':
      return encoding10
    case '@tamaflow/rag-search-result':
      return encoding11
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
